version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tutoring-calendar-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tutoring_calendar
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: tutoring-calendar-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
